version: "3.8"
services:
  gbert_api:
    build:
      context: ./gbert
    ports:
      - "8000:8000"
    restart: always
    command: ["uvicorn", "agent_gbert:app", "--host", "0.0.0.0", "--port", "8000"]

  flan_t5_api:
    build:
      context: ./flan-t5-base
    ports:
      - "8001:8000"
    restart: always
    command: ["uvicorn", "agent_flan_t5:app", "--host", "0.0.0.0", "--port", "8000"]

  distillbert_api:
    build:
      context: ./distillbert
    ports:
      - "8002:8000"
    restart: always
    command: ["uvicorn", "agent_distillbert:app", "--host", "0.0.0.0", "--port", "8000"]
